language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-support
  - extra-android-m2repository
env:
  global:
  - IJK_HASH=k0.8.3
  - IJK_REPO=https://github.com/Bilibili/ijkplayer.git
before_install:
- sudo apt-get install -y git
- sudo apt-get install -y yasm
- jdk_switcher use oraclejdk8
before_script:
- wget "https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip"
- mkdir -p $HOME/android-ndk-root
- unzip android-ndk-r10e-linux-x86_64.zip -d $HOME/android-ndk-root > /dev/null
- export ANDROID_NDK=$HOME/android-ndk-root/android-ndk-r10e
- git clone --depth=50 --branch=$IJK_HASH $IJK_REPO
- cd ijkplayer
- "./init-android.sh"
- cd android
- "./build-on-travis.sh all"
script:
- echo "FINISHED"
