language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-support
  - extra-android-m2repository
env:
  global:
  - IJK_HASH=k0.8.3
  - IJK_REPO=https://github.com/Bilibili/ijkplayer.git
  - secure: HtGB+Z6xh0LzQiyNPlZGy/T9TX/heGsGXgIGh/+FneRFS5RrcKB3hPbWVCrvGYv0YngxMSVfAy6gz3ENBESHiCEBIaU6d2LCZvN4jjsDF53X7tZCxLX4APqaLYFc+lS8NmAQ7oAmzVKRBy7fdUS47sHkW3hqsRtEfLuJGX6aPUeO4i4/14NkH1ncolIR/jL4AAHQsN48qz3Zx0ngr8U1hxr38bT6MYNu+HC9LeuRPO2q/sFV/kRvLaMlBezZcW8qjb2TVyrsVrkmk1pbvP2f1eiqjXm0eE+auCKbBWUy1tOey8c/bpvbtX8MPfE5d6yXyXt5lbTLmGcIcEmI4zMedcR4wyMW3RodOxOCge/TibQ4zMxejGcjg+K2g2b9VowZaUD3PSVZoDLHDd5wVPehnwa0XDAwwJNVni6g0XNNCN2XUln1L174LZl5HJN0gz8WtU5fGOlLhCQMqd8M1KFQiu350bRAvBFua6wlDv/Er3yJF6fO1m/bTMbs+TZnQk8f8zCl12lGU99ay4pzydYWkugLKEYx68dxc8nI7D7SSMzsyQ01jnZCofuAAUr3MB/6EdgCwZJDwwE5fsdP8DvxgyyQly/jWH2PjUcOrS5BXtsDd5f3xflM2djH2NJCqT0TUyX00oF2hPBbWDnWFZOMN5v94tSzRDZEjhabptm229c=
  - secure: eLWWxQdNnm6TDDFHyXH1kU4usRb0o3FszsA7vlx1h1uLTrO41LrbVtgo8diVs7nI43Yy7+AoA/+VJ4mI9Tce6UojAofMfi+xx5/OCf+eoTnhHsM088GaYimIvg8fuE3AywvcJgKSW64nmZgGGl2XT2MO+g5J8ff6jCROylE4IGPMCljztHQ9VZIXk5ouzbTQZhL1QENN5zxd7kN4kKR976kh6qIrkkqvLUA+Nwwv23SbzjhA9VYk8TQxR4YqVkYmLmQgdPIGyUR3+vpi2Rdc73GqsFKMBtKNYDgRNMrIegaJDwtGl2jhkJv1sh4lGQMS4YSHvZWg3MbyBMX+8/WayaFpoJ5zoaD9faE3DbT1qq1WllwHCRwbk9WRxd9y/GGPO5pHD60GTVsXcXgoruJAXh3s4aA6Ri+eS4FmQWrhFuReu4bP6chrLE9OVB3+/YfOlIIAanhtV6FLyVGFV39o3ae2eQ+4p5zYmELbA1ac6rT0bv1H7nkpdFVmbldOo72ueOCcFUoqCasddoiQqMS0NA26mrCswvYV70C6ScSXIQ0OBLjpLXd03W588HNdN9JDV4FMPU66i66oMztqdF3X2yWFLImjLRMrHPVSREiPHefQxzrdbGG3WKTAfOTkLG0B7rFM4YFTNox/iHmDLSVFw7JSb1p9NH5QHd/tzx3EQUc=
  - secure: J5T5tfyrJ8s2U79TMtXLag2MS7sLPHAfL7AqyA0AKexk20phok3AVyrWX0v9kqZoTXBofkzKjkTjZ9Ic/G58r9Ua0dkBr01InGd1rw8cHN86Ln9IR9Zo8jvW+LvEkUbmeig/JEMa0Pk+2Q1SyXMQ70FxPQ75F1GHTxVVUxbitLvCVvIg//WJ6egKs4NhGaxa17QjjCszaC0diehch6WBC9DIeIICT0daYIRQ3yOUCOXRZRkCEU0if1Ya7r8+ZZNYNldUX1rD7GYXq76o7Dy51jOer9Xal59Oek5XTEaxkhjPCOUnccG3lDIl6h+8LjEaRnfP0PJuuT0s64dY436oda+NmkMHhdeXys83fmSlinzc55rB1TT2ZAtvCx5RL7sU5w1/bHalGstQZYGjJ0XQvO4kcB+B9LOKFjzWECV5pHjQY+bAugFYW821BDnollHeHT1960IlI1ToH4E/4qSgiLTIhIGG35kRyBpqfkmhFkbYe9Hc5mZHqlmgeq3FCuteOWn3vzI3szOIgWHSP1stG+o3yrrz6S3s2qbiHGLfaT0ugRL4wuFVfCntX4of+BlZxIJgmlHdYc2jOQGnRX+JAsaWmdPuVDyX9Hk0DX7ZkmUW484XNwGaP8ZOOuJ75SxHIgpC2kDzoP4qevugjzzNuXl/7aT75TwvKicQ4cu4bLA=
before_install:
- sudo apt-get install -y git
- sudo apt-get install -y yasm
- jdk_switcher use oraclejdk8
before_script:
- wget "https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip"
- mkdir -p $HOME/android-ndk-root
- unzip android-ndk-r10e-linux-x86_64.zip -d $HOME/android-ndk-root > /dev/null
- export ANDROID_NDK=$HOME/android-ndk-root/android-ndk-r10e
- git clone --depth=50 --branch=$IJK_HASH $IJK_REPO
- cd ijkplayer
- "./init-android.sh"
- cd android
- "./build-on-travis.sh all"
script:
- echo "FINISHED"
