language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-support
  - extra-android-m2repository
env:
  global:
  - IJK_HASH=k0.8.3
  - IJK_REPO=https://github.com/Bilibili/ijkplayer.git
  - secure: Wt0gz3cV8Z4iBU9csZCwoTQ5ZkJLMERbF6FVoHG9Pd7ax9AI/w39cdGlw8hYrtIOWloTOS5sRrog0EGV/6IWRH87YaBAVL3He2yBY4u5qO6gnYmxHRWX2pIGvooKrKkiNXEyXp32mYsE8v5fHziirb6R7vCPooXkxe329GMnCFALfjVInwhlrdCJsXds5FxRnLhzCfytpwmeur8jIL8fmutK2HxWBX3OCAVn8PGWY5CDNw54btXRKTDiQbVoAF63hQLmTrXVIcAF9oXwQeHF6RG7T1YQKPJkC4kZKX+O0bQEXQ/TX/oOwR5dhcEF3tdAn5LlWn9Z2o2oL0PqVSJI+cUKbZxaY35NCggxY1gt77Pk65zyfRMbpOLeBZcfjwHtjPt35FO4TIeWZRfalseO30lAsPDFOaRGPB0xOVRSFZJz8yWQ6P1X0sLWyJqJ00MFly2wbNE5M8vV/prYTwauF7gdh39Nfsu5e2Uatx7OmoZV9PngU5LWX1Kna49P0Nk/RS7ngF7YKigxjmFZCWmk6un1bJlflN1/na3Uos+mtLgyPD8QbE4QN0MAuymqsy0+MH701NQMNk5+PTkbPvPlPfsWCy2FnNysaQGS1keIMl/U8NAFlvCCAnkcg5l3Z4XcVF2G/w/mskM0KXXNxNiCgCiJWIxitR92b4uxpLORMzQ=
  - secure: KRrywb+XMLwb2rOWF31B2c83GlsLrVQ+pqFAQpilNNkVmwIVv3N0XSKFuiCkdC9eRWJnGJEZp9+CzNMtrGKIiy4ppcbqu5Z89QS2BJNdz0h7Vm1xhbJ0d8H3gajvFEznCNr6V2x/sCykNsaUGaXYSDAHahQxr2OJlRJDRA/J3IKN8vdeS+gugun0wNAoinCXtA5pX4yOUKYn0u0Fqs0hrz4Cck05mE+dzF43T71EIe0zvIva8yx3272rWDGUD08aTK09kvWbyrRa1LDaKb4rM6jtr4X9mqehUZKF7Op4mW7wbJICi2fmxsgXCgZI7koar985uwBG7v6PD/GIKwaJfXcf1zVMof+aYzokTAGusvMH8BxRq3pHtNMc4gxpPkeLhfqlyDTkEcuyUAjYqzdn2R0hZkIgPvrU/v9MDku58oP94ILTNX285JNX1vqc/9MIEzYyrtQ3vpeEAKe+q+V5/EFR0IhriyaTpCmvgnINhR/QCcgYW6Ug+bvlqQIn0IMhk+dgviDgD9PODkd7BrMS6JUU8BJmDSRlVD1dEZiEoVI/8+/sSnD31hewZVe9xAnpra1Kwa7bY2bi5Whgy3kUwIGZUpsRDuOow3KR0oT0Jv+AdDRotHigPlCp1GIkK8V1LJ2Ddzf0LoaMJdmmtc70r30aJirI0fSJKtdHQbTGx0M=
  - secure: hK1UC6UY7yupuFjSb2vVFtmhFVtnDDOxfmAd463N43oYN4s0Ngz2kexEV34XNlvAU9gDnjiyakYjZ4uA2i/uXX+3ioQJPKgcwdMFw/iu4tgXbJ3Oh3wSN+9VMr8D1No+Xn7slXTxRzrUjPko8hkimv18qzMcN9jvx75NzgQKrWjdKq4stjyrxcQ64XnJWykkGdEdErRGyYdD+EQ26XFWpjSz3h/OWD7XjKSTzHZyD1/4+IT+Wd5PK8zZlIsbS+i0HKpz4FIPLEllU3dnxffPFG99E07sNCl7SEMBSLZeb/4WuDBUJJM+GuTxOMf4vboCIJXY6qjXkJUmmQK5etutu3PIxsOauD0B9UL3FW59JgdKRL6ZX572IWPzk6ldzcwFXpzAgrglU4SmzdMUyqtJBetng4GtCbbJGMkkgl/7Od/UpbVEhV2+T4vKOUe9hKNcKWKW+g3qYTLJnStlil2dbu+IEER9vNANn5hETZD1hDGrY33m1Qs3LxQu2Wa8Su4Elb+VPKp5oSjNRZl+Q6eY1WIIC/phZbLbQ1Z3XoRZSGdX8lQ2KuMUhG/7fENypC7JsID1LepNYepuEJvlOf7iN0FBfw02qy0kXWhkL9GpXLfwvPVUY715vmgcOJALjUn7c20R40f3IcaAv3w3ln55nrGLDm5TIZh0gNl/pVo5OLU=
before_install:
- sudo apt-get install -y git
- sudo apt-get install -y yasm
- jdk_switcher use oraclejdk8
before_script:
- wget "https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip"
- mkdir -p $HOME/android-ndk-root
- unzip android-ndk-r10e-linux-x86_64.zip -d $HOME/android-ndk-root > /dev/null
- export ANDROID_NDK=$HOME/android-ndk-root/android-ndk-r10e
- git clone --depth=50 --branch=$IJK_HASH $IJK_REPO
- cd ijkplayer
- "./init-android.sh"
- cd android
- "./build-on-travis.sh all"
script:
- echo "FINISHED"
